version: "3.9"

services:

  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"           # expose to host so you can use Compass locally
    volumes:
      - mongo_data:/data/db    # data persists across container restarts
    environment:
      MONGO_INITDB_DATABASE: finrisk

  app:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      MONGO_URI: mongodb://mongo:27017   # 'mongo' = service name above, not localhost
      MONGO_DB:  finrisk
    depends_on:
      - mongo                  # wait for mongo to start before app

volumes:
  mongo_data:
